config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'words#index'
  resources :words do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :word
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :words
  has_many :comments
end

app/models/word.rb
class Word < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search != ""
      Word.where('name LIKE(?)', "%#{search}%")
    else
      Word.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/words/#{comment.word.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, word_id: params[:word_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @words = user.words
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]
  def index
    @words = Word.includes(:user).order("created_at DESC")
  end

  def new
    @word = Word.new
  end

  def create
    Word.create(word_params)
  end

  def destroy
    word = Word.find(params[:id])
    word.destroy
  end
  
  def edit
  end

  def update
    word = Word.find(params[:id])
    word.update(word_params)
  end

  def show
    @comment = Comment.new
    @comments = @word.comments.includes(:user)
  end

  def search
    @words = Word.search(params[:keyword])
  end
  
  private
  def word_params
    params.require(:word).permit(:name, :language, :meaning, :example, :resources).merge(user_id: current_user.id)
  end
  
  def set_word
    @word = Word.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Programming Words</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
    <div class="h_wrapper">
      <h1><a href="/">Programming Words</a></h1>
      <%# ↓PCメニュー %>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to "マイページ", "/users/#{current_user.id}", class: "header_btn" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_btn" %>
          <%= link_to "単語登録する", new_word_path, class: "post", class: "header_btn" %>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: "header_btn" %>
          <%= link_to "新規登録", new_user_registration_path, class: "header_btn" %>
        </div>
      <% end %>
      <%# ↓スマホメニュー %>
      <div class="sp_nemu">
        <input type="checkbox" id="nav_input" class="nav_invisible">
        <label id="nav_open" for="nav_input"><span></span></label>
        <div class="nav_contents">
          <% if user_signed_in? %>
            <div class="sp_user_nav">
              <%= link_to "マイページ", "/users/#{current_user.id}", class: "sp_header_btn" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "sp_header_btn" %>
              <%= link_to "単語登録する", new_word_path, class: "post", class: "sp_header_btn" %>
            </div>
          <% else %>
            <div class="sp_user_nav">
              <%= link_to "ログイン", new_user_session_path, class: "sp_header_btn" %>
              <%= link_to "新規登録", new_user_registration_path, class: "sp_header_btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </header>
    <%= yield %>
    <footer>
      <div class="f_wrapper">
        <p class="f_text">© 2021 TomonoriYoshimura</p>
      </div>
    </footer>
</body>
</html>

app/views/users/show.html.erb
<div class="m_wrapper">
<p class="nickname_title"><%= @nickname %>さんの登録した単語</p>
  <% @words.each do |word| %>
    <%= render partial: "words/word", locals: { word: word } %>
  <% end %>
</div>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <div class="name_field">
    <%= form.text_field :name, placeholder: "プログラミング用語", class: 'text_form' %>
  </div>
  <div class="language_field">
    <%= form.text_field :language, placeholder: "言語", class: 'text_form' %>
  </div>
  <div class="meaning_field">
    <%= form.text_area :meaning, placeholder: "意味 / 内容", rows: "10", class: 'text_form' %>
  </div>
  <%# <div class="meaning_field"> %>
    <%# form.text_field :resources, placeholder: "情報源", class: 'text_form' %>
  <%# </div> %>
  <div class="example_field">
    <%= form.text_area :example, placeholder: "例", rows: "10", class: 'text_form' %>
  </div>
  <div class="form_btn_wrapper">
    <%= form.submit "登録", class: "form_btn" %>
    <a href="/" class="form_btn">戻る</a>
  </div>
<% end %>

app/views/words/_word.html.erb
<div class="name">
  <%= word.name %>
</div>
<div class="meaning text_display">
  <p class="text_left">意味</p>
  <p class="text_right"><%= safe_join(word.meaning.split("\n"), tag(:br)) %></p>
</div>
<div class="example text_display">
  <p class="text_left">例 ）</p>
  <p class="text_right text_ex"><%= word.example %></p>
</div>
<%# <div class="resources text_display">
  <p class="text_left">情報源</p>
  <p class="text_right">word.resources</p>
<%# </div> %>
<div class="language text_display">
  <p class="text_left">言語</p>
  <p class="text_right"><%= word.language %></p>
</div>
<div class="btn_wrapper">
  <%= link_to '詳細', word_path(word.id), method: :get, class: "btn" %>
  <% if user_signed_in? && current_user.id == word.user_id %>
    <%= link_to '編集', edit_word_path(word.id), method: :get, class: "btn" %>
    <%= link_to '削除', word_path(word.id), method: :delete, class: "btn" %>
  <% end %>
</div>

app/views/words/create.html.erb
<div class="m_wrapper">
<div class="title_wrapper">
  <h3 class="end_title">登録が完了しました。</h3>
</div>
  <div class="toppage_btn_wrapper">
    <a href="/" class="toppage_btn">トップページへ戻る</a>
  </div>
</div>

app/views/words/destroy.html.erb
<div class="m_wrapper">
<div class="title_wrapper">
  <h3 class="end_title">削除が完了しました。</h3>
</div>
  <div class="toppage_btn_wrapper">
    <a href="/" class="toppage_btn">トップページへ戻る</a>
  </div>
</div>

app/views/words/edit.html.erb
<div class="m_wrapper">
  <div class="title_wrapper">
    <h3 class="h3_title">編集する</h3>
  </div>
  <%= render partial: "form", locals: { word: @word } %>
</div>

app/views/words/index.html.erb
<main>
  <%= form_with(url: search_words_path, local: true, method: :get, class: "search_form") do |form| %>
    <%= form.text_field :keyword, placeholder: "単語を検索する", class: "search_input" %>
    <%= form.submit "検索", class: "search_btn", id: "search_js" %>
  <% end %>


  <div class="m_wrapper search_dis">
    <% @words.each do |word| %>
      <%= render partial: "word", locals: { word: word } %>
    <% end %>
  </div>
</main>

app/views/words/new.html.erb
<div class="m_wrapper">
  <div class="title_wrapper">
    <h3 class="h3_title">登録する</h3>
  </div>
  <%= render partial: "form", locals: { word: @word } %>
</div>

app/views/words/search.html.erb
<main>
  <%= form_with(url: search_words_path, local: true, method: :get, class: "search_form") do |form| %>
    <%= form.text_field :keyword, placeholder: "単語を検索する", class: "search_input" %>
    <%= form.submit "検索", class: "search_btn" %>
  <% end %>

  <div class="m_wrapper">
    <% @words.each do |word| %>
      <%= render partial: "word", locals: { word: word } %>
    <% end %>
  </div>
</main>

app/views/words/show.html.erb
<div class="m_wrapper">
    <div class="name">
      <%= @word.name %>
    </div>
    <div class="meaning text_display">
      <p class="text_left">意味</p>
      <p class="text_right"><%= @word.meaning %></p>
    </div>
    <div class="example text_display">
      <p class="text_left">例 ）</p>
      <p class="text_right"><%= @word.example %></p>
    </div>
    <div class="language text_display">
      <p class="text_left">言語</p>
      <p class="text_right"><%= @word.language %></p>
    </div>

    <% if user_signed_in? && current_user.id == @word.user_id %>
      <div class="btn_wrapper">
        <%= link_to '編集', edit_word_path(@word.id), method: :get, class: "btn" %>
        <%= link_to '削除', word_path(@word.id), method: :delete, class: "btn" %>
        <a href="/" class="btn">戻る</a>
      </div>
    <% end %>

    <div class="comment_form_wrapper">
      <% if user_signed_in? %>
        <%= form_with(model: [@word, @comment], local: true, class: "form_with") do |form| %>
          <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "comment_form" %>
          <%= form.submit "SEND", class: "form_btn" %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
      <h4 class="comment_list">＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
</div>

app/views/words/update.html.erb
<div class="m_wrapper">
<div class="title_wrapper">
  <h3 class="end_title">登録が完了しました。</h3>
</div>
  <div class="toppage_btn_wrapper">
    <a href="/" class="toppage_btn">トップページへ戻る</a>
  </div>
</div>